services:
  app:
    container_name: vulcan
    image: vulcan
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/vulcan
    # Optionally, specify environment variables
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    # You can also specify ports if necessary
    #command: php-fpm  # Example command to run PHP in a production environment
    # Dependencies, like databases, can be linked here
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - .:/var/www/vulcan
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: vulcan_mysql_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: